version: '2'

services:
  wordpress:
    image: wordpress:4.5.2
    environment:
      WORDPRESS_DB_PASSWORD: whatever
    volumes:
      - ./:/var/www/html/wp-content/themes/twentyeleven-development
    ports:
      - 6789:80

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: whatever
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
